### ISSUE TITLE
Load data from JSON and toggle navigation menu + add blur

### ISSUE THREAD

**Issue by Tarupotter** [MagnusTerak/Group-d-assignment#57]
**Description**
I want the website to dynamically load content from a JSON file and display it on the page and I want to be able to toggle the navigation menu by clicking on the menu icon in mobile view.

**User story**
as a website visitor, I want to easily display the navigation bar by clicking the menu button.

**Tasks**
- [ ] fetch data from json file
- [ ] toggle the menu
- [ ] add blur to rest of page when menu is open

**Connected PBIS**
#14 
#55
